---
# tasks file for sabnzbd

- name: Add Repository "only final stable releases"
  apt_repository:
    repo: ppa:jcfp/nobetas
    state: present

- name: Add Repository "sab-addons"
  apt_repository:
    repo: ppa:jcfp/sab-addons
    state: present

- name: Install Sabnzbd
  package:
     name: "{{ item }}"
     state: present
  with_items:
     - sabnzbdplus
#     - python-sabyenc

- name: Create Sabnzbd directory
  file: path={{ sabnzbd_path }} owner={{ htpc_user_username }} group={{ htpc_user_group }} state=directory mode=0755

- name: Create Sabnzbd Incomplete downloads folders
  file: path={{ item }} state=directory owner={{ htpc_user_username }} group={{ htpc_user_group }} mode=0777 recurse=yes
  with_items:
    - "{{ sabnzbd_incomplete }}"

- name: Update Sabnzbd configuration
  template: src=sabnzbd.ini.j2 dest={{ sabnzbd_path }}/sabnzbd.ini owner={{ htpc_user_username }} group={{ htpc_user_group }} mode=0644
  notify:
    - restart sabnzbd

- name: Update Sabnzbd Daemon configuration
  template: src=etc_default_sabnzbd.j2 dest=/etc/default/sabnzbdplus owner=root group=root mode=0644
  notify:
    - restart sabnzbd

- name: Make sure Sabnzbd is running and started on boot
  service: name=sabnzbdplus state=started enabled=yes
